version: '3'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=astrea-web
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    ports:
      - '8081:80'
    depends_on:
      - mysql
